"""Migração Inicial

Revision ID: 829dbc995255
Revises: 
Create Date: 2024-09-09 17:02:27.842826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829dbc995255'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('data_pedido', sa.Date(), nullable=True),
    sa.Column('valor_total', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    # ### end Alembic commands ###
